### ISSUE TITLE
Revise and distribute technical documents to Agora

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/AgoraMainNet#14]
The site we need to refer to is as follows.

https://ethereum.org/en/developers/ 
https://geth.ethereum.org/
https://docs.prylabs.network/

**Comment by TrustHenry** [comment]
https://docs.bosagora.org

**Comment by hewison-chris** [comment]
https://agora-cl-docs.bosagora.org/ is forked from https://docs.prylabs.network
