### ISSUE TITLE
Test Validator exit works with Agora-cl

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/AgoraMainNet#77]
Follow the `Validator Exit` procedure and verify that it works correctly.

**Comment by MichaelKim20** [comment]
I created a keyset with only one validator, and deposited 40,000 test boa. 
And the validator was executed for a certain period of time.
Since then, I have executed the following command.

**Test Environment**

1. This is the key set I tested.
[validator_keys12.zip](https://github.com/bosagora/AgoraMainNet/files/9805636/validator_keys12.zip)

2. I used branch `testnet` of `https://github.com/bosagora/agora-chain`

**Command**
docker run -it  -v $(pwd)/root/:/root --name cl-validator --rm bosagora/agora-cl-validator:v1.0.0 accounts voluntary-exit -wallet-dir=/root/wallet

** Execution Log**
```
Prysmatic Labs Terms of Use

By downloading, accessing or using the Prysm implementation (“Prysm”), you (referenced herein
as “you” or the “user”) certify that you have read and agreed to the terms and conditions below.

TERMS AND CONDITIONS: https://github.com/zeroone-boa/prysm/blob/agora/TERMS_OF_SERVICE.md


Type "accept" to accept this terms and conditions [accept/decline]: (default: decline):
accept
[2022-10-18 01:21:43]  WARN flags: Running on Ethereum Mainnet
Wallet password: 
[2022-10-18 01:21:48]  WARN validator: You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc
Done with selections
Are you sure you want to perform a voluntary exit on 0 accounts? () Y/N:
Y
===============IMPORTANT===============
Withdrawing funds is not possible in Phase 0 of the system. Please navigate to the following website and make sure you understand the current implications of a voluntary exit before making the final decision:
https://docs.prylabs.network/docs/wallet/exiting-a-validator/#withdrawal-delay-warning
If you still want to continue with the voluntary exit, please input a phrase found at the end of the page from the above URL:
Exit my validator
[2022-10-18 01:23:32] FATAL accounts: Could not perform voluntary exit error=rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused"
```

**Comment by hewison-chris** [comment]
Tested using https://github.com/bosagora/local-testnet with command:
```
docker run -it -v /Users/chrishewison/ZEROONE/local-testnet/beacon/data/beacon-val:/root --name cl-validator --network exec_priv-eth-net --rm prysm-validator:local accounts voluntary-exit --accept-terms-of-use  -wallet-dir=/root/wallet --beacon-rpc-provider beacon-1:4000
```


![Image](https://user-images.githubusercontent.com/11815575/196342628-f9bbb947-d489-416d-965e-bf9ff4cb0124.png)

**Comment by hewison-chris** [comment]
Some documentation updates for the agora-cl validator: https://github.com/bosagora/agora-cl/pull/34

**Comment by hewison-chris** [comment]
Some documentation updates for agora-cl-docs: https://github.com/bosagora/agora-cl-docs/pull/26

**Comment by MichaelKim20** [comment]
@hewison-chris Show me how Agora DevNet works

**Comment by hewison-chris** [comment]
On AWS Devnet node AgoraDevNet-Consensus-Layer5: 13.229.80.56
```
docker run -it -v $HOME/.eth2validators/prysm-wallet-v2:/wallet --network="host" --name cl-val --rm bosagora/agora-cl-validator:v1.0.0 accounts voluntary-exit --accept-terms-of-use  -wallet-dir=/wallet --beacon-rpc-provider 127.0.0.1:4000
```
<img width="995" alt="Screen Shot 2022-10-19 at 10 06 13" src="https://user-images.githubusercontent.com/11815575/196573605-e8249cef-9941-48f4-b37b-2d7c34e63c0f.png">

**Comment by hewison-chris** [comment]
Some updates are in progress for the incorrect links and output etc.
But the exit does work.

**Comment by hewison-chris** [comment]
<img width="996" alt="Screen Shot 2022-10-19 at 10 14 20" src="https://user-images.githubusercontent.com/11815575/196574299-540c7e03-8a7b-400b-a545-6016f05d0a70.png">

**Comment by MichaelKim20** [comment]
@hewison-chris I've confirmed that it's going well. Thank you for everything.
