### ISSUE TITLE
Agora-Scan - Please correct the part marked in red in the attached document

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/AgoraMainNet#79]
[ChangeCaption.pdf](https://github.com/bosagora/AgoraMainNet/files/9810706/ChangeCaption.pdf)

**Comment by hewison-chris** [comment]
<img width="527" alt="Screen Shot 2022-10-19 at 10 57 42" src="https://user-images.githubusercontent.com/11815575/196579346-9f17f852-de3a-4d70-8703-b76cd3ad245b.png">
<img width="1568" alt="Screen Shot 2022-10-19 at 10 58 24" src="https://user-images.githubusercontent.com/11815575/196579436-344f8988-0e8d-403b-a27a-457ab86c3a27.png">
<img width="1534" alt="Screen Shot 2022-10-19 at 10 58 54" src="https://user-images.githubusercontent.com/11815575/196579489-114c47a6-aefe-4a42-a775-9860a53f1043.png">
<img width="1506" alt="Screen Shot 2022-10-19 at 11 00 08" src="https://user-images.githubusercontent.com/11815575/196579628-55af2d42-ce96-4c06-bf13-7ece735acd47.png">

**Comment by hewison-chris** [comment]
https://github.com/bosagora/agora-scan/pull/38
