### ISSUE TITLE
Remove from Agora-cl and Agora-cl-docs non docker deployment

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/AgoraMainNet#80]
The Prysm project supports many deployment options but to keep it simple and less error prone we are only supporting the use of docker for the Agora-cl consensus layer client.

We should remove the `prysm.bat`, `prysm.ps1` and `prysm.sh` scripts and documents that describe using them and update to use the docker commands or the agora.sh script from the agora-chain project.

**Comment by MichaelKim20** [comment]
https://github.com/bosagora/agora-cl-docs/pull/28
