### ISSUE TITLE
We need a unified Favicon of the sites we made.

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/AgoraMainNet#81]
<img width="1167" alt="스크린샷 2022-10-19 오후 3 15 04" src="https://user-images.githubusercontent.com/48541289/196611375-e2eff9a1-b4cb-4660-a4b3-97afafe5d5c3.png">

**Comment by Kang-Simon** [comment]
boa-scan : https://github.com/bosagora/boa-scan/pull/61

**Comment by Kang-Simon** [comment]
agora-scan : https://github.com/bosagora/agora-scan/pull/3

**Comment by Kang-Simon** [comment]
agora-staking : https://github.com/bosagora/agora-staking/pull/94
