### ISSUE TITLE
Change the sentence

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/AgoraMainNet#82]
Each deposit is registered by the consensus chain after a block delay of 2048 Ethereum 1.0 blocks
->
Each deposit is registered by the consensus chain after a block delay of 2048 Agora-el blocks

<img width="1412" alt="스크린샷 2022-10-19 오후 5 45 28" src="https://user-images.githubusercontent.com/11639939/196642650-9519211d-4ebe-4062-8a64-35d3a14e51a8.png">

**Comment by TrustHenry** [comment]
https://github.com/bosagora/agora-scan/pull/39
