### ISSUE TITLE
Agora Staking - 문구들을 수정해주세요

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/AgoraMainNet#83]
수정해야 할 부분을 정리해서 PDF로 올립니다.
[Agora-Staking-review1.pdf](https://github.com/bosagora/AgoraMainNet/files/9826435/Agora-Staking-review1.pdf)

**Comment by Kang-Simon** [comment]
https://github.com/bosagora/agora-staking/pull/87

**Comment by MichaelKim20** [comment]
<img width="1286" alt="스크린샷 2022-10-20 오후 5 39 47" src="https://user-images.githubusercontent.com/11639939/196900161-370bd501-693f-41a2-8b89-7c646788e4b8.png">

본 문중에서 다음 내용을 변경해 주세요

중요한 것은 검증인으로서 BOA 을(를) 담보로 전송해야 한다는 것입니다. 즉, 일부 자금이 예치되어 있어야 합니다. 검증자가 되는 유일한 방법은 현재 BOSAGORA 체인의 **예금** 스마트 컨트랙트에 대해 단방향으로 BOA 를 예치하는 것입니다.

=>

중요한 것은 검증인으로서 BOA 을(를) 담보로 전송해야 한다는 것입니다. 즉, 일부 자금이 예치되어 있어야 합니다. 검증자가 되는 유일한 방법은 현재 BOSAGORA 체인의 **예치** 스마트 컨트랙트에 대해 단방향으로 BOA 를 예치하는 것입니다.

**Comment by MichaelKim20** [comment]
그리고 링크는 다음에 일괄 수정해 주세요

**Comment by Kang-Simon** [comment]
https://github.com/bosagora/AgoraMainNet/issues/83#issuecomment-1285154066 https://github.com/bosagora/agora-staking/pull/88
