### ISSUE TITLE
Be prepared to provide check-point of Agora-cl.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/AgoraMainNet#91]
Downloading a slot that has not been synchronized from another node is called sync.
To speed this up, we need to establish a system that provides a stable and reliable check-point.

**Comment by MichaelKim20** [comment]
Reference) https://agora-cl-docs.bosagora.org/docs/agora-cl-usage/checkpoint-sync

**Comment by MichaelKim20** [comment]
First, we need to test `Weak Subjectivity Checkpoint` on the test net.
See) https://medium.com/prysmatic-labs/prysmatic-labs-ethereum-development-update-3a26150fd449

**Comment by TrustHenry** [comment]
https://github.com/bosagora/agora-chain/pull/42

**Comment by TrustHenry** [comment]
https://notes.ethereum.org/@adiasg/weak-subjectvity-eth2#Distributing-Weak-Subjectivity-Checkpoint-States

**Comment by TrustHenry** [comment]
https://hackmd.io/@prysmaticlabs/r1ZUuXTMt

**Comment by MichaelKim20** [comment]
Good

**Comment by MichaelKim20** [comment]
Good
